### ISSUE TITLE
Use an image as the button?

### ISSUE THREAD

**Issue by Sweeper777** [ruddfawcett/RFKeyboardToolbar#10]
I want to use a picture of a slanted "I" as a button on the toolbar, like this:

![italic_000000_25](https://cloud.githubusercontent.com/assets/13585047/22772793/9f2b0f04-ee96-11e6-8b23-049250f982ab.png)

I can't find any constructors that accept an image, so i tried this:

```swift
let italicButton = RFToolbarButton(title: "", andEventHandler: { 
  // function
}, for: .touchUpInside)!
italicButton.setImage(UIImage(named: "italic"), for: .normal)
italicButton.setImage(UIImage(named: "ialic"), for: .highlighted)
textView.inputAccessoryView = RFKeyboardToolbar(buttons: [italicButton])
```
But the button did not appear on the toolbar.

**Comment by ruddfawcett** [comment]
I've never actually tried using images for buttons, so I'm not sure how to really help out. You could also try setting an attributed string instead, if you're going for the italic effect?

**Comment by Sweeper777** [comment]
Okay. I'll use custom fonts then.
