### ISSUE TITLE
The user has to tap on the spacing between the buttons to scroll.

### ISSUE THREAD

**Issue by Sweeper777** [ruddfawcett/RFKeyboardToolbar#15]
I have many buttons on my toolbar, when I try to scroll it, I found that I cannot scroll it unless I start my touch on the the little spaces between the buttons, otherwise the button that I touched will be pressed. 

Can this somehow be handled? If the gesture is a pan, can the button not be triggered and instead the toolbar will scroll?

**Comment by ruddfawcett** [comment]
That sounds like it could work — feel free to send in PR!

**Comment by Sweeper777** [comment]
Actually I have no idea how to do this... and I know little Objective-C, so I can't really do that...
